[package]
name = "tesserv"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { version = "1.8.3", features = ["mmap", "rayon"] }
clap = { version = "4.5.60", features = ["derive"] }
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["multipart", "server"] }
